# .github/actions/setup-subtopia-registry/action.yaml
name: "Setup Subtopia Registry"
description: "Setup Subtopia Registry"
inputs:
  ssh-key:
    description: "SSH Key"
    required: true
  repository:
    description: "Repository"
    required: true
  path:
    description: "Path"
    required: true
  node-version:
    description: "Node Version"
    required: true
  python-version:
    description: "Python Version"
    required: true
  poetry-version:
    description: "Poetry Version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out registry infra setup
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ inputs.ssh-key }}
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: main
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Poetry
      shell: sh
      run: |
        pip install pipx
        pipx install poetry

    - name: Run AlgoKit LocalNet
      shell: sh
      run: |
        cd registry-infra
        pipx install algokit
        algokit localnet start
        time sleep 10

    - name: Setup localnet registry
      shell: sh
      env:
        LOCALNET_APP_IDS_PATH: ${{ github.workspace }}/.env
        CHAIN_TYPE: localnet
      run: |
        cp .env.template .env
        cd registry-infra
        poetry install --no-interaction
        poetry run pip install setuptools
        cat ${{ github.workspace }}/.env
        poetry run python3 admin_scripts/deploy_localnet_infra.py
        cat ${{ github.workspace }}/.env
